-- DROP SCHEMA store;

CREATE SCHEMA store AUTHORIZATION postgres;

-- DROP SEQUENCE store.store_checkout_id_seq;

CREATE SEQUENCE store.store_checkout_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE store.store_checkout_item_id_seq;

CREATE SEQUENCE store.store_checkout_item_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE store.store_customer_id_seq;

CREATE SEQUENCE store.store_customer_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE store.store_employee_id_seq;

CREATE SEQUENCE store.store_employee_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE store.store_item_id_seq;

CREATE SEQUENCE store.store_item_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE store.store_item_order_id_seq;

CREATE SEQUENCE store.store_item_order_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE store.store_order_id_seq;

CREATE SEQUENCE store.store_order_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE store.store_supplier_id_seq;

CREATE SEQUENCE store.store_supplier_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;


-- store.store_customer definition

-- Drop table

-- DROP TABLE store.store_customer;

CREATE TABLE store.store_customer (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	customername varchar(30) NULL,
	CONSTRAINT store_customer_pkey PRIMARY KEY (id)
);


-- store.store_employee definition

-- Drop table

-- DROP TABLE store.store_employee;

CREATE TABLE store.store_employee (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	employeename varchar(30) NULL,
	CONSTRAINT store_employee_pkey PRIMARY KEY (id)
);


-- store.store_item definition

-- Drop table

-- DROP TABLE store.store_item;

CREATE TABLE store.store_item (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	itemname varchar(30) NULL,
	shelfprice money NULL,
	CONSTRAINT store_item_pkey PRIMARY KEY (id)
);


-- store.store_supplier definition

-- Drop table

-- DROP TABLE store.store_supplier;

CREATE TABLE store.store_supplier (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	suppliername varchar(30) NULL,
	CONSTRAINT store_supplier_pkey PRIMARY KEY (id)
);


-- store.store_checkout definition

-- Drop table

-- DROP TABLE store.store_checkout;

CREATE TABLE store.store_checkout (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	customerid int4 NULL,
	employeeid int4 NULL,
	checkoutdate date NULL,
	taxamount money NULL,
	CONSTRAINT store_checkout_pkey PRIMARY KEY (id),
	CONSTRAINT store_checkout_customerid_fkey FOREIGN KEY (customerid) REFERENCES store.store_customer(id),
	CONSTRAINT store_checkout_employeeid_fkey FOREIGN KEY (employeeid) REFERENCES store.store_employee(id)
);


-- store.store_checkout_item definition

-- Drop table

-- DROP TABLE store.store_checkout_item;

CREATE TABLE store.store_checkout_item (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	itemid int4 NULL,
	checkoutid int4 NULL,
	quantity int4 NULL,
	actualprice numeric(14, 2) NULL,
	CONSTRAINT store_checkout_item_pkey PRIMARY KEY (id),
	CONSTRAINT store_checkout_item_checkoutid_fkey FOREIGN KEY (checkoutid) REFERENCES store.store_checkout(id),
	CONSTRAINT store_checkout_item_itemid_fkey FOREIGN KEY (itemid) REFERENCES store.store_item(id)
);


-- store.store_order definition

-- Drop table

-- DROP TABLE store.store_order;

CREATE TABLE store.store_order (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	supplierid int4 NULL,
	datepurchased date NULL,
	received boolean NULL,
	paid boolean NULL,
	CONSTRAINT store_order_pkey PRIMARY KEY (id),
	CONSTRAINT store_order_supplierid_fkey FOREIGN KEY (supplierid) REFERENCES store.store_supplier(id),
	CONSTRAINT store_order_employeeid_fkey FOREIGN KEY (employeeid) REFERENCES store.store_employee(id)
);


-- store.store_order_item definition

-- Drop table

-- DROP TABLE store.store_order_item;

CREATE TABLE store.store_order_item (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	itemid int4 NULL,
	orderid int4 NULL,
	quantity int4 NULL,
	actualprice numeric(14, 2) namespace NULL,
	CONSTRAINT store_item_order_pkey PRIMARY KEY (id),
	CONSTRAINT store_item_order_itemid_fkey FOREIGN KEY (itemid) REFERENCES store.store_item(id),
	CONSTRAINT store_item_order_orderid_fkey FOREIGN KEY (orderid) REFERENCES store.store_order(id)
);
